/*
 * generated by Xtext 2.24.0
 */
package de.fraunhofer.ipa.componentInterface.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractComponentInterfaceScopeProvider extends DelegatingScopeProvider {
}
